Repository lfglabs-dev/starknet.quest, pull requests merged in 2024-05, with the labels that each got.

#627 feat/leaderboard_v2 setup
  app/leaderboard/page.tsx
  components/UI/iconsComponents/icons/Rank2Icon.tsx
  components/UI/iconsComponents/icons/Rank3Icon.tsx
  components/UI/iconsComponents/icons/rank1Icon.tsx
  components/leaderboard/ControlsDashboard.tsx
  components/leaderboard/RankCard.tsx
  components/leaderboard/RankingsTable.tsx
  components/leaderboard/Top3RankedUsers.tsx
  components/navbar/walletButton.tsx
  constants/common.ts
  styles/components/chiplist.module.css
  styles/leaderboard.module.css
  types/frontTypes.d.ts
Labels: 🔥 Ready for review

#662 fix: starknetid.js version
  package-lock.json
  package.json
Labels: 🔥 Ready for review

#666 fix: update starknet-react to latest version
  app/provider.tsx
  components/UI/navbar.tsx
  context/StarknetIdJsProvider.tsx
  package-lock.json
  package.json
Labels: 🔥 Ready for review

#664 feat: add haiko quest NFT image
  public/haiko/favicon.ico
  public/haiko/haikoStrategist.webp
Labels: 🔥 Ready for review

#667 MEP 03/05/2024
  app/provider.tsx
  components/UI/navbar.tsx
  context/StarknetIdJsProvider.tsx
  package-lock.json
  package.json
  public/haiko/favicon.ico
  public/haiko/haikoStrategist.webp
Labels: 🚧 In progress do not merge

#599 feat: add dashboard
  .gitignore
  app/[addressOrDomain]/page.tsx
  app/achievements/page.tsx
  app/analytics/[questId]/page.tsx
  app/leaderboard/page.tsx
  app/quest-boost/[boostId]/page.tsx
  app/quest-boost/claim/[boostId]/page.tsx
  app/quest-boost/page.tsx
  components/UI/actions/socialmediaActions.tsx
  components/UI/avatar.tsx
  components/UI/footer.tsx
  components/UI/iconsComponents/icons/closeFilledIcon.tsx
  components/UI/iconsComponents/icons/copyIcon.tsx
  components/UI/iconsComponents/icons/shareIcon.tsx
  components/UI/navbar.tsx
  components/UI/profileCard/profileCard.tsx
  components/UI/profileCards.tsx
  components/dashboard/CustomisedQuestCard.tsx
  components/leaderboard/RankCard.tsx
  components/leaderboard/Top3RankedUsers.tsx
  components/pages/home/howToParticipate.tsx
  components/pages/home/questAndCollectionTabs.tsx
  components/quest-boost/boostCard.tsx
  components/quests/quest.tsx
  components/quests/questCard.tsx
  components/quests/questDetails.tsx
  components/skeletons/QuestCardSkeleton.tsx
  components/skeletons/dashboardSkeleton.tsx
  components/skeletons/profileCardSkeleton.tsx
  components/skeletons/questsCompletedTitleSkeleton.tsx
  components/skeletons/questsSkeleton.tsx
  constants/common.ts
  context/QuestsProvider.tsx
  hooks/useCreationDate.ts
  jest.config.js
  package-lock.json
  package.json
  public/icons/share.svg
  services/apiService.ts
  services/starknetIdService.ts
  styles/Home.module.css
  styles/components/navbar.module.css
  styles/dashboard.module.css
  tests/services/apiService.test.js
  tests/utils/browserService.test.js
  tests/utils/numberService.test.js
  tests/utils/profile.test.js
  tests/utils/stringService.test.js
  types/backTypes.d.ts
  types/frontTypes.d.ts
  utils/browserService.ts
  utils/cdnize.ts
  utils/numberService.ts
  utils/profile.ts
  utils/stringService.ts
Labels: 🔥 Ready for review

#672 MEP 06/04/2025
  .gitignore
  app/[addressOrDomain]/page.tsx
  app/achievements/page.tsx
  app/analytics/[questId]/page.tsx
  app/leaderboard/page.tsx
  app/quest-boost/[boostId]/page.tsx
  app/quest-boost/claim/[boostId]/page.tsx
  app/quest-boost/page.tsx
  components/UI/actions/socialmediaActions.tsx
  components/UI/avatar.tsx
  components/UI/footer.tsx
  components/UI/iconsComponents/icons/closeFilledIcon.tsx
  components/UI/iconsComponents/icons/copyIcon.tsx
  components/UI/iconsComponents/icons/shareIcon.tsx
  components/UI/navbar.tsx
  components/UI/profileCard/profileCard.tsx
  components/UI/profileCards.tsx
  components/dashboard/CustomisedQuestCard.tsx
  components/leaderboard/RankCard.tsx
  components/leaderboard/Top3RankedUsers.tsx
  components/pages/home/howToParticipate.tsx
  components/pages/home/questAndCollectionTabs.tsx
  components/quest-boost/boostCard.tsx
  components/quests/quest.tsx
  components/quests/questCard.tsx
  components/quests/questDetails.tsx
  components/skeletons/QuestCardSkeleton.tsx
  components/skeletons/dashboardSkeleton.tsx
  components/skeletons/profileCardSkeleton.tsx
  components/skeletons/questsCompletedTitleSkeleton.tsx
  components/skeletons/questsSkeleton.tsx
  constants/common.ts
  context/QuestsProvider.tsx
  hooks/useCreationDate.ts
  jest.config.js
  package-lock.json
  package.json
  public/icons/share.svg
  services/apiService.ts
  services/starknetIdService.ts
  styles/Home.module.css
  styles/components/navbar.module.css
  styles/dashboard.module.css
  tests/services/apiService.test.js
  tests/utils/browserService.test.js
  tests/utils/numberService.test.js
  tests/utils/profile.test.js
  tests/utils/stringService.test.js
  types/backTypes.d.ts
  types/frontTypes.d.ts
  utils/browserService.ts
  utils/cdnize.ts
  utils/numberService.ts
  utils/profile.ts
  utils/stringService.ts
Labels: 🔥 Ready for review

#684 fix: notification loading
  components/navbar/walletButton.tsx
  hooks/useNotificationManager.ts
Labels: 🔥 Ready for review

#687 feat: add expired quest page
  app/categories/[category]/page.tsx
  app/quest/[questPage]/quest.tsx
  components/quests/nftImage.tsx
  components/quests/questDetails.tsx
  context/QuestsProvider.tsx
  services/apiService.ts
Labels: 🔥 Ready for review

#635 test: get_quests
  app/analytics/page.tsx
  context/QuestsProvider.tsx
  services/apiService.ts
  tests/services/apiService.test.js
  types/backTypes.d.ts
Labels: ❌ Change request

#686 Feat/view quests to claim rewards
  app/[addressOrDomain]/page.tsx
  components/UI/iconsComponents/icons/reward.tsx
  components/pages/home/questAndCollectionTabs.tsx
  components/quests/questCard.tsx
  components/quests/questClaim.tsx
  styles/quests.module.css
  tests/utils/quest.test.js
  types/backTypes.d.ts
  types/frontTypes.d.ts
  utils/quest.ts
Labels: ❌ Change request

#689 MEP 14/05/2024
  app/[addressOrDomain]/page.tsx
  app/analytics/page.tsx
  app/categories/[category]/page.tsx
  app/quest/[questPage]/quest.tsx
  components/UI/iconsComponents/icons/reward.tsx
  components/pages/home/questAndCollectionTabs.tsx
  components/quests/nftImage.tsx
  components/quests/questCard.tsx
  components/quests/questClaim.tsx
  components/quests/questDetails.tsx
  context/QuestsProvider.tsx
  services/apiService.ts
  styles/components/quests/quiz.module.css
  styles/quests.module.css
  tests/services/apiService.test.js
  tests/utils/quest.test.js
  types/backTypes.d.ts
  types/frontTypes.d.ts
  utils/quest.ts
Labels: 🔥 Ready for review

#710 MEP 29/05/2024
  app/layout.tsx
  public/bountive/bountiveJackpot.webp
  public/bountive/favicon.ico
Labels: 🔥 Ready for review

#711 feat: add updated bountive image
  public/bountive/bountiveJackpot.webp
Labels: 🔥 Ready for review
