Repository lfglabs-dev/starknet.quest, pull requests merged in 2024-10, with the labels that each got.

#848 fixed progressBar bug
  components/UI/progressBar.tsx
  styles/components/progressBar.module.css
Labels: ❌ Change request

#843 added new contract task type in the admin dashboard
  app/admin/quests/create/page.tsx
  app/admin/quests/dashboard/[questId]/page.tsx
  components/admin/formSteps/TaskDetailsForm.tsx
  components/admin/taskSteps/contractStep.tsx
  constants/admin.ts
  services/authService.ts
  types/backTypes.d.ts
  types/frontTypes.d.ts
Labels: ❌ Change request

#834 feat: update sid.js
  components/UI/notifications/notificationDetail.tsx
  components/navbar/walletButton.tsx
  context/StarknetIdJsProvider.tsx
  hooks/useNotificationManager.ts
  package-lock.json
  package.json
Labels: 🔥 Ready for review

#860 refactor: Remove user percentile ranking from ProfileCard component
  components/UI/profileCard/profileCard.tsx
Labels: ❌ Change request

#856 Create Reusable Loading Component and implement it
  app/admin/quests/page.tsx
  app/loading.tsx
Labels: ❌ Change request

#861 Refactor: Merge clickable social media icon component
  components/UI/actions/clickable/clickableDiscordIcon.tsx
  components/UI/actions/clickable/clickableGithubIcon.tsx
  components/UI/actions/clickable/clickableSocialIcon.tsx
  components/UI/actions/clickable/clickableTwitterIcon.tsx
  components/UI/actions/socialmediaActions.tsx
Labels: ❌ Change request

#870 feat: add claim reward flow
  components/discover/appIcon.tsx
  components/discover/claimModal.tsx
  components/discover/defiTable.tsx
  components/discover/successModal.tsx
  components/discover/tokenIcon.tsx
Labels: 🚧 In progress do not merge

#874 feat: pyramid quest
  public/pyramid/favicon.ico
  public/pyramid/ticket.webp
Labels: 🔥 Ready for review

#873 fix: quest not loading in admin dashboard
  app/admin/quests/page.tsx
Labels: 🔥 Ready for review

#875 feat: reward aggregator
  components/discover/claimModal.tsx
  components/discover/defiTable.tsx
  public/nostra/favicon.ico
  services/apiService.ts
  types/backTypes.d.ts
  types/frontTypes.d.ts
Labels: 🔥 Ready for review

#892 feat: layerakira images
  public/layerakira/favicon.ico
  public/layerakira/raven.webp
Labels: 🔥 Ready for review

#898 feat: add Opus protocol information (#897)
  package-lock.json
  public/opus/favicon.ico
  utils/defi.ts
Labels: 🔥 Ready for review

#900 fix: Links Map in defi.ts
  utils/defi.ts
Labels: ❌ Change request

#919 reward claim function added in dashboard fix:#913
  components/dashboard/PortfolioSummary.tsx
Labels: ❌ Change request
